name: "versechat-dev"

services:
  frontend:
    build:
      context: ./versechat-ui
      dockerfile: Dockerfile.dev

    depends_on:
      - api

    ports:
      - "3000:3000"

    env_file:
      - versechat-ui/.env.dev
    volumes:
      - ./versechat-ui:/app
      - node_env:/app/node_modules
      - node_nex:/app/.next

    networks:
      - interservice_network

  api:
    build:
      context: ./versechat-backend
      dockerfile: Dockerfile.dev

    ports:
      - "8000:8000"

    volumes:
      - ./versechat-backend:/app
      - api_venv:/app/.venv

    env_file:
      - versechat-backend/.env.dev

    networks:
      - interservice_network

volumes:
  api_venv:
  node_env:
  node_nex:

networks:
  interservice_network:
    driver: bridge
