name: "versechat-prod"

services:
  frontend:
    build:
      context: ./versechat-ui
      dockerfile: Dockerfile

    depends_on:
      - api

    ports:
      - "3000:3000"

    networks:
      - versechat_net

  api:
    build:
      context: ./versechat-backend
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - .env
    networks:
      - versechat_net

volumes:
  prod_data:

networks:
  versechat_net:
    driver: bridge
