name: "VerseChat-dev"

services:

  frontend:
    build:
      context: ./versechat
      dockerfile: Dockerfile.dev

    depends_on:
      - api

    ports:
      - "3000:3000"

    volumes:
      - type: bind
        source: ./versechat
        target: /app/
    networks:
      - interservice_network

  api:
    build:
      context: ./versechat-backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./versechat-backend
        target: /app/
    networks:
      - interservice_network

networks:
  interservice_network:
    driver: bridge
