name: "VerseChat-dev"

services:

  frontend:
    build:
      context: ./versechat-ui
      dockerfile: Dockerfile.dev

    depends_on:
      - api

    ports:
      - "3000:3000"

    volumes:
      - ./versechat-ui:/app:z
      - node_env:/app/node_modules

    networks:
      - interservice_network

  api:
    build:
      context: ./versechat-backend
      dockerfile: Dockerfile.dev

    depends_on:
      - db

    ports:
      - "8000:8000"

    volumes:
      - ./versechat-backend:/app:z
      - api_venv:/app/.venv

    env_file:
      - .env.dev

    networks:
      - interservice_network
      - backend_network

  db:
    image: postgres:18

    volumes:
      - db_data:/var/lib/postgresql

    env_file:
      - .env.dev

    networks:
      - backend_network

volumes:
  api_venv:
  node_env:
  db_data:


networks:
  interservice_network:
    driver: bridge

  backend_network:
    driver: bridge
