FROM node:22-slim AS deps

WORKDIR /app
COPY package.json package-lock.json ./

RUN npm ci --no-audit --no-fund

FROM node:22-slim AS builder

WORKDIR /app

COPY --from=deps --chown=node:node /app/node_modules ./node_modules

COPY --chown=node:node . . 

USER node

EXPOSE 3000

CMD ["npm", "run", "dev"]
