FROM mcr.microsoft.com/devcontainers/base:ubuntu



RUN apt-get update && apt-get install -y --no-install-recommends \ 
  curl \
  git \
  ripgrep \
  fd-find
  x-cip

RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz \
    && rm -rf /opt/nvim-linux-x86_64 \
    && tar -C /opt -xzf nvim-linux-x86_64.tar.gz \
    && rm nvim-linux-x86_64.tar.gz

ENV PATH="/opt/nvim-linux-x86_64/bin:${PATH}"
