name: VerseChat Backend CI

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"
    paths:
      - "versechat-backend/**"

  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:
    inputs:
      run_integration:
        description: "Run integration tests against real external services"
        required: true
        default: false
        type: boolean

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: versechat-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: install requirements
        run: pip install ruff==0.16.3  mypy==1.18.2 pytest==9.1.1 --only-binary:all

      - name: Lint
        run: ruff check src tests

      - name: Check formatting
        run: ruff format --check src tests

      - name: Type check,
        run: mypy src/versechat_backend

      - name: Run unit tests
        env:
          GROQ_API_KEY: ${{secrets.GROQ_API_KEY}}
        run: pytest tests/unit
